src/Entity/Plan.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PlanRepository")
 */
class Plan
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\User", inversedBy="plans")
     */
    private $user;

    /**
     * @ORM\Column(type="string", length=10)
     */
    private $code;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $competence;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $indicator;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $activity;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $deleted_at;

    /**
     * @ORM\Column(type="integer")
     */
    private $created_by;

    public function __construct()
    {
        $this->user = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return Collection|User[]
     */
    public function getUser(): Collection
    {
        return $this->user;
    }

    public function addUser(User $user): self
    {
        if (!$this->user->contains($user)) {
            $this->user[] = $user;
        }

        return $this;
    }

    public function removeUser(User $user): self
    {
        if ($this->user->contains($user)) {
            $this->user->removeElement($user);
        }

        return $this;
    }

    public function getCode(): ?string
    {
        return $this->code;
    }

    public function setCode(string $code): self
    {
        $this->code = $code;

        return $this;
    }

    public function getCompetence(): ?string
    {
        return $this->competence;
    }

    public function setCompetence(?string $competence): self
    {
        $this->competence = $competence;

        return $this;
    }

    public function getIndicator(): ?string
    {
        return $this->indicator;
    }

    public function setIndicator(?string $indicator): self
    {
        $this->indicator = $indicator;

        return $this;
    }

    public function getActivity(): ?string
    {
        return $this->activity;
    }

    public function setActivity(?string $activity): self
    {
        $this->activity = $activity;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(): self
    {
        $this->created_at = new \DateTime();

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(): self
    {
        $this->updated_at = new \DateTime();;

        return $this;
    }

    public function getDeletedAt(): ?\DateTimeInterface
    {
        return $this->deleted_at;
    }

    public function setDeletedAt(\DateTimeInterface $deleted_at): self
    {
        $this->deleted_at = $deleted_at;

        return $this;
    }

    public function getCreatedBy(): ?int
    {
        return $this->created_by;
    }

    public function setCreatedBy(int $created_by): self
    {
        $this->created_by = $created_by;

        return $this;
    }
}

src/Form/PlanType.php
<?php

namespace App\Form;

use App\Entity\Plan;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PlanType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('code')
            ->add('competence')
            ->add('indicator')
            ->add('activity')
            //->add('created_at')
            //->add('updated_at')
            //->add('deleted_at')
            //->add('created_by')
            //->add('user')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Plan::class,
        ]);
    }
}

src/Controller/PlanController.php
<?php

namespace App\Controller;

use App\Entity\Plan;
use App\Form\PlanType;
use App\Repository\PlanRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/plan")
 */
class PlanController extends AbstractController
{
    /**
     * @Route("/", name="plan_index", methods={"GET"})
     */
    public function index(PlanRepository $planRepository): Response
    {
        $user = $this->getUser();
        return $this->render('plan/index.html.twig', [
            'plans' => $planRepository->findByUser($user->getId()),
        ]);
    }

    /**
     * @Route("/new", name="plan_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $plan = new Plan();
        $form = $this->createForm(PlanType::class, $plan);
        $form->handleRequest($request);
        $user = $this->getUser();

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $plan->setCreatedAt();
            $plan->setUpdatedAt();
            $plan->setCreatedBy($user->getId());
            $plan->addUser($user);
            $entityManager->persist($plan);
            $entityManager->flush();

            return $this->redirectToRoute('plan_index');
        }

        return $this->render('plan/new.html.twig', [
            'plan' => $plan,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="plan_show", methods={"GET"})
     */
    public function show(Plan $plan): Response
    {
        return $this->render('plan/show.html.twig', [
            'plan' => $plan,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="plan_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Plan $plan): Response
    {
        $form = $this->createForm(PlanType::class, $plan);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('plan_index');
        }

        return $this->render('plan/edit.html.twig', [
            'plan' => $plan,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="plan_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Plan $plan): Response
    {
        if ($this->isCsrfTokenValid('delete'.$plan->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($plan);
            $entityManager->flush();
        }

        return $this->redirectToRoute('plan_index');
    }
}

templates/plan/_delete_form.html.twig
<form method="post" action="{{ path('plan_delete', {'id': plan.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ plan.id) }}">
    <button class="btn">Delete</button>
</form>

templates/plan/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/plan/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Plan{% endblock %}

{% block body %}
    <h1>Edit Plan</h1>

    {{ include('plan/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('plan_index') }}">back to list</a>

    {{ include('plan/_delete_form.html.twig') }}
{% endblock %}

templates/plan/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Plan index{% endblock %}

{% block body %}
    <h1>Plan index</h1>

    <div class="table-responsive">

        <table class="table">
            <thead>
                <tr>
                    <th>No.</th>
                    <th>Code</th>
                    <th>Competence</th>
                    <th>Indicator</th>
                    <th>Activity</th>
                    <th>Created_at</th>
                    <th>Updated_at</th>
                    <th>Created_by</th>
                    <th>actions</th>
                </tr>
            </thead>
            <tbody>
            {% for i, plan in plans %}
                <tr>
                    <td>{{ i+1 }}</td>
                    <td>{{ plan.code }}</td>
                    <td>{{ plan.competence }}</td>
                    <td>{{ plan.indicator }}</td>
                    <td>{{ plan.activity }}</td>
                    <td>{{ plan.createdAt ? plan.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                    <td>{{ plan.updatedAt ? plan.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
                    <td>{{ plan.createdBy }}</td>
                    <td>
                        <a href="{{ path('plan_show', {'id': plan.id}) }}">show</a>
                        <a href="{{ path('plan_edit', {'id': plan.id}) }}">edit</a>
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="10">no records found</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

    <a href="{{ path('plan_new') }}">Create new</a>
{% endblock %}

templates/plan/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Plan{% endblock %}

{% block body %}
    <h1>Create new Plan</h1>

    {{ include('plan/_form.html.twig') }}

    <a href="{{ path('plan_index') }}">back to list</a>
{% endblock %}

templates/plan/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Plan{% endblock %}

{% block body %}
    <h1>Plan</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ plan.id }}</td>
            </tr>
            <tr>
                <th>Code</th>
                <td>{{ plan.code }}</td>
            </tr>
            <tr>
                <th>Competence</th>
                <td>{{ plan.competence }}</td>
            </tr>
            <tr>
                <th>Indicator</th>
                <td>{{ plan.indicator }}</td>
            </tr>
            <tr>
                <th>Activity</th>
                <td>{{ plan.activity }}</td>
            </tr>
            <tr>
                <th>Created_at</th>
                <td>{{ plan.createdAt ? plan.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Updated_at</th>
                <td>{{ plan.updatedAt ? plan.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Deleted_at</th>
                <td>{{ plan.deletedAt ? plan.deletedAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Created_by</th>
                <td>{{ plan.createdBy }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('plan_index') }}">back to list</a>

    <a href="{{ path('plan_edit', {'id': plan.id}) }}">edit</a>

    {{ include('plan/_delete_form.html.twig') }}
{% endblock %}